### ISSUE TITLE
Random 'nope' error

### ISSUE THREAD

**Issue by benjackwhite** [keajs/kea-subscriptions#1]
On this line an error is logged simply saying "nope" https://github.com/keajs/kea-subscriptions/blob/8f8a6a38b351044e1271907a781f5d822f582942/src/index.ts#L81

Managed to get this to happen in PostHog and tracked it down to here 😅

**Comment by mariusandra** [comment]
Version 3.0.1 has been released for your enjoyment with a slightly better error:

```ts
console.error(`[KEA] Subscription Failed for action ${action.type} on logic ${sub.logic.pathString}.`)
console.error(error)
```
